#!/bin/bash
# Skript kuvab muudetava suurusega õõnsa ruudustiku

read -p "Sisesta ridade arv: " read_arv
read -p "Sisesta tärnide arv reas: " tarn_arv

for (( i=1; i<=read_arv; i++ ))
do
    for (( j=1; j<=tarn_arv; j++ ))
    do
        if [[ $i -eq 1 || $i -eq $read_arv || $j -eq 1 || $j -eq $tarn_arv ]]
        then
            echo -n "* "
        else
            echo -n "  "
        fi
    done
    echo ""
done
