#!/bin/bash
# Skript kuvab diagonaaliga ruudustiku

read -p "Sisesta ridade arv: " read_arv

for (( i=1; i<=read_arv; i++ ))
do
    for (( j=1; j<=read_arv; j++ ))
    do
        if [[ $j -gt $((read_arv-i)) ]]
        then
            echo -n "* "
        else
            echo -n "o "
        fi
    done
    echo ""
done
